# Generated by Django 4.2.4 on 2023-09-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
